#!/usr/bin/env zsh

DIRTY="✗"
NONE="✓"

prompt_amartinescalera_pwd() {
  prompt_short_dir=$(dot filesystem short_pwd)
  print -n "%F{yellow}${prompt_short_dir}"
}

prompt_amartinescalera_git() {
  [[ -n ${git_info} ]] && print -n "%F{white}(${(e)git_info[prompt]})"
}

prompt_amartinescalera_precmd() {
  (( ${+functions[git-info]} )) && git-info
}

prompt_amartinescalera_setup() {
  local prompt_amartinescalera_status='%(?:%F{blue}{%F{white}am%F{blue}:%F{red}{%F{white}am%F{red})'

  autoload -Uz add-zsh-hook && add-zsh-hook precmd prompt_amartinescalera_precmd

  prompt_opts=(cr percent sp subst)

  zstyle ':zim:git-info:branch' format '%F{blue}%b'
  zstyle ':zim:git-info:commit' format '%c'
  zstyle ':zim:git-info:clean' format '%F{white}'
  zstyle ':zim:git-info:dirty' format '%F{yellow}$DIRTY'
  zstyle ':zim:git-info:keys' format 'prompt' '%F{cyan}%b%c %C%D'

  PS1="${prompt_amartinescalera_status} \$(prompt_amartinescalera_pwd)\$(prompt_amartinescalera_git)%f "
  RPS1=''
}

prompt_amartinescalera_setup "${@}"
