#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? do the login to pcf
#?? 1.0.0
##?
##? Usage:
##?   login <url>
docs::eval "$@"

cf login -a $1 --sso --skip-ssl-validation

echo "😬 Dooone!"