#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? do the login to pcf
#?? 1.0.0
##?
##? Usage:
##?   push <manifest> <filename>
docs::eval "$@"

cf push -f $1 -p $2

echo "😬 Dooone!"