#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Search tns inside a folder
#?? 1.0.0
#?? folder
#?? dbname
#?? /Users/amartin/projects/optima/documents/tsnames
##?
##? Usage:
##?     search <folder> <dbname>
docs::eval "$@"

find $1 -name "*.ora" | xargs grep "$2"

echo "😬 Dooone!"