#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Kill process named
#?? 1.0.0
##?
##? Usage:
##?   kill_named
docs::eval "$@"

find . -name "*.iml" -exec rm {} \;

echo 'done!'
